# Generated by Django 5.2.6 on 2025-10-28 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_variation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="variation",
            old_name="Variation_category",
            new_name="variation_category",
        ),
    ]
