# Generated by Django 5.2.6 on 2025-11-05 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_productgallery"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productgallery",
            options={
                "verbose_name": "product gallery",
                "verbose_name_plural": "product gallery",
            },
        ),
    ]
