# Generated by Django 5.2.6 on 2025-10-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0002_rename_quantity_cartitem_quantity"),
        ("store", "0003_rename_variation_category_variation_variation_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="variations",
            field=models.ManyToManyField(blank=True, to="store.variation"),
        ),
    ]
