# Generated by Django 5.2.6 on 2025-10-31 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="account",
            managers=[],
        ),
    ]
