# Generated by Django 5.2.6 on 2025-11-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="static/images/default_profile_picture.png",
                upload_to="userprofile/",
            ),
        ),
    ]
