# Generated by Django 5.2.6 on 2025-11-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_userprofile_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, default="images/default.png", upload_to="userprofile"
            ),
        ),
    ]
